// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RobotNeverDie

//@version=4
study("Ticker", shorttitle="Ticker", overlay=false)

// Description:
// Find if current ticker has quote currency.
//
// More at https://github.com/robotneverdie-algo/Pine-Script

//{=================================================================================== Misc. Functions =====================================================================================}

has_quote(quote) =>
    syminfo.currency == quote

_quote = input("BTC", type=input.string, title="Quote")
var _has_quote = has_quote(_quote)
plot(_has_quote ? 1 : 0)
